// <auto-generated />
using System;
using CommonBaseData.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommonBaseData.Migrations
{
    [DbContext(typeof(Contexts))]
    partial class ContextsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Arabic_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommonBaseData.Model.TblCommonBaseDatum", b =>
                {
                    b.Property<int>("CommonBaseDataId")
                        .HasColumnType("int");

                    b.Property<string>("BaseCode")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("BaseValue")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int?>("CommonBaseTypeId")
                        .HasColumnType("int");

                    b.HasKey("CommonBaseDataId");

                    b.HasIndex(new[] { "BaseCode", "CommonBaseTypeId" }, "IX_tblBaseCode")
                        .IsUnique()
                        .HasFilter("[BaseCode] IS NOT NULL AND [CommonBaseTypeId] IS NOT NULL");

                    b.ToTable("tblCommonBaseData");
                });
#pragma warning restore 612, 618
        }
    }
}
